#!/usr/bin/env node
/**
 * Regenerate the inlined base64 Linear logo used by the filter macro UI.
 *
 * Reads: static/linear-logo.png
 * Writes: src/modules/filterMacro/linear-logo-data.js
 *
 * Run this after replacing static/linear-logo.png with a new image.
 *
 * Usage: node scripts/encode-logo.js
 */

const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const src = path.join(root, 'static', 'linear-logo.png');
const out = path.join(root, 'src', 'modules', 'filterMacro', 'linear-logo-data.js');

if (!fs.existsSync(src)) {
  console.error(`Source logo not found at ${src}`);
  process.exit(1);
}

const stats = fs.statSync(src);
const b64 = fs.readFileSync(src).toString('base64');

const body =
  '// Auto-generated from static/linear-logo.png by scripts/encode-logo.js\n' +
  '// Do not edit this file directly. Replace static/linear-logo.png and rerun the script.\n' +
  'module.exports = "data:image/png;base64,' +
  b64 +
  '";\n';

fs.writeFileSync(out, body);

console.log(`OK: ${stats.size.toLocaleString()} bytes PNG -> ${b64.length.toLocaleString()} base64 chars`);
console.log(`Wrote ${path.relative(root, out)}`);
